// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var NoteAudioRecordingErrors = &noteAudioRecordingErrors{
	ErrUniqueNoteAudioRecordingPkey: &UniqueConstraintError{
		schema:  "",
		table:   "note_audio_recording",
		columns: []string{"uuid"},
		s:       "note_audio_recording_pkey",
	},
}

type noteAudioRecordingErrors struct {
	ErrUniqueNoteAudioRecordingPkey *UniqueConstraintError
}
