// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var NoteErrors = &noteErrors{
	ErrUniqueNotePkey: &UniqueConstraintError{
		schema:  "",
		table:   "note",
		columns: []string{"uuid"},
		s:       "note_pkey",
	},
}

type noteErrors struct {
	ErrUniqueNotePkey *UniqueConstraintError
}
