// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TaskAudioReviewErrors = &taskAudioReviewErrors{
	ErrUniqueTaskAudioReviewPkey: &UniqueConstraintError{
		schema:  "",
		table:   "task_audio_review",
		columns: []string{"id"},
		s:       "task_audio_review_pkey",
	},
}

type taskAudioReviewErrors struct {
	ErrUniqueTaskAudioReviewPkey *UniqueConstraintError
}
