-- +goose Up

ALTER TABLE FS_PointLocation ADD COLUMN ASSIGNEDTECH TEXT;
ALTER TABLE FS_PointLocation ADD COLUMN deactivate_reason TEXT;
ALTER TABLE FS_Pool ADD COLUMN VECTORSURVCOLLECTIONID TEXT;
ALTER TABLE FS_Pool ADD COLUMN VECTORSURVPOOLID TEXT;
ALTER TABLE FS_Pool ADD COLUMN VECTORSURVTRAPDATAID TEXT;
CREATE TABLE FS_RodentLocation (
	ACCESSDESC TEXT,
	ACTIVE INT2,
	COMMENTS TEXT,
	CreationDate BIGINT,
	Creator TEXT,
	DESCRIPTION TEXT,
	EXTERNALID TEXT,
	EditDate BIGINT,
	Editor TEXT,
	GlobalID TEXT,
	HABITAT TEXT,
	LASTINSPECTACTION TEXT,
	LASTINSPECTCONDITIONS TEXT,
	LASTINSPECTDATE BIGINT,
	LASTINSPECTRODENTEVIDENCE TEXT,
	LASTINSPECTSPECIES TEXT,
	LOCATIONNAME TEXT,
	LOCATIONNUMBER INT8,
	NEXTACTIONDATESCHEDULED BIGINT,
	OBJECTID INTEGER PRIMARY KEY,
	PRIORITY TEXT,
	SYMBOLOGY TEXT,
	USETYPE TEXT,
	ZONE TEXT,
	ZONE2 TEXT,
	created_date BIGINT,
	created_user TEXT,
	geometry_x FLOAT,
	geometry_y FLOAT,
	last_edited_date BIGINT,
	last_edited_user TEXT);
ALTER TABLE FS_ServiceRequest ADD COLUMN DOG INT8;
ALTER TABLE FS_ServiceRequest ADD COLUMN Spanish INT8;
ALTER TABLE FS_ServiceRequest ADD COLUMN schedule_notes TEXT;
ALTER TABLE FS_ServiceRequest ADD COLUMN schedule_period TEXT;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN vs_id;
ALTER TABLE FS_TrapData ADD COLUMN Lure TEXT;
ALTER TABLE FS_TrapData ADD COLUMN VECTORSURVTRAPDATAID TEXT;
ALTER TABLE FS_TrapData ADD COLUMN VECTORSURVTRAPLOCATIONID TEXT;
ALTER TABLE FS_TrapData DROP COLUMN vs_id;
ALTER TABLE FS_TrapLocation ADD COLUMN VECTORSURVSITEID TEXT;
ALTER TABLE FS_TrapLocation DROP COLUMN vs_id;

-- +goose Down
ALTER TABLE FS_PointLocation DROP COLUMN ASSIGNEDTECH;
ALTER TABLE FS_PointLocation DROP COLUMN deactivate_reason;
ALTER TABLE FS_Pool DROP COLUMN VECTORSURVCOLLECTIONID;
ALTER TABLE FS_Pool DROP COLUMN VECTORSURVPOOLID;
ALTER TABLE FS_Pool DROP COLUMN VECTORSURVTRAPDATAID;
DROP TABLE FS_RodentLocation;
ALTER TABLE FS_ServiceRequest DROP COLUMN DOG;
ALTER TABLE FS_ServiceRequest DROP COLUMN Spanish;
ALTER TABLE FS_ServiceRequest DROP COLUMN schedule_notes;
ALTER TABLE FS_ServiceRequest DROP COLUMN schedule_period;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN vs_id TEXT;
ALTER TABLE FS_TrapData DROP COLUMN Lure;
ALTER TABLE FS_TrapData DROP COLUMN VECTORSURVTRAPDATAID;
ALTER TABLE FS_TrapData DROP COLUMN VECTORSURVTRAPLOCATIONID;
ALTER TABLE FS_TrapData ADD COLUMN vs_id TEXT;
ALTER TABLE FS_TrapLocation DROP COLUMN VECTORSURVSITEID;
ALTER TABLE FS_TrapLocation ADD COLUMN vs_id TEXT;
