-- +goose Up
ALTER TABLE FS_MosquitoInspection ADD COLUMN adminAction TEXT;
ALTER TABLE FS_PointLocation ADD COLUMN scalarPriority INT8;
ALTER TABLE FS_PointLocation ADD COLUMN sourceStatus TEXT;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN globalZScore DOUBLE PRECISION;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN h3r7 TEXT;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN h3r8 TEXT;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN r7Score DOUBLE PRECISION;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN r8Score DOUBLE PRECISION;
ALTER TABLE FS_SpeciesAbundance ADD COLUMN yearWeek INT8;
ALTER TABLE FS_TrapLocation ADD COLUMN h3r7 TEXT;
ALTER TABLE FS_TrapLocation ADD COLUMN h3r8 TEXT;

-- +goose Down
ALTER TABLE FS_MosquitoInspection DROP COLUMN adminAction TEXT;
ALTER TABLE FS_PointLocation DROP COLUMN scalarPriority INT8;
ALTER TABLE FS_PointLocation DROP COLUMN sourceStatus TEXT;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN globalZScore DOUBLE PRECISION;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN h3r7 TEXT;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN h3r8 TEXT;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN r7Score DOUBLE PRECISION;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN r8Score DOUBLE PRECISION;
ALTER TABLE FS_SpeciesAbundance DROP COLUMN yearWeek INT8;
ALTER TABLE FS_TrapLocation DROP COLUMN h3r7 TEXT;
ALTER TABLE FS_TrapLocation DROP COLUMN h3r8 TEXT;
