-- +goose Up

ALTER TABLE FS_MosquitoInspection ADD COLUMN PTAID TEXT;
ALTER TABLE FS_RodentLocation ADD COLUMN JURISDICTION TEXT;
ALTER TABLE FS_TimeCard ADD COLUMN RODENTLOCID TEXT;
ALTER TABLE History_MosquitoInspection ADD COLUMN PTAID TEXT;
ALTER TABLE History_RodentLocation ADD COLUMN JURISDICTION TEXT;
ALTER TABLE History_TimeCard ADD COLUMN RODENTLOCID TEXT;

-- +goose Down
ALTER TABLE FS_MosquitoInspection DROP COLUMN PTAID;
ALTER TABLE FS_RodentLocation DROP COLUMN JURISDICTION;
ALTER TABLE FS_TimeCard DROP COLUMN RODENTLOCID;
ALTER TABLE History_MosquitoInspection DROP COLUMN PTAID;
ALTER TABLE History_RodentLocation DROP COLUMN JURISDICTION;
ALTER TABLE History_TimeCard DROP COLUMN RODENTLOCID;
