-- +goose Up

ALTER TABLE FS_MosquitoInspection ADD COLUMN PTAID TEXT;
ALTER TABLE FS_RodentLocation ADD COLUMN JURISDICTION TEXT;
ALTER TABLE FS_TimeCard ADD COLUMN jODENTLSOCID TEXT;

-- +goose Down
ALTER TABLE FS_MosquitoInspection DROP COLUMN PTAID TEXT;
ALTER TABLE FS_RodentLocation DROP COLUMN JURISDICTION TEXT;
ALTER TABLE FS_TimeCard DROP COLUMN RODENTLSOCID TEXT;
