// Code generated by BobGen psql v0.41.1. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"math"
	"strconv"
	"strings"
	"time"

	enums "github.com/Gleipnir-Technology/fieldseeker-sync/database/enums"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
)

var defaultFaker = faker.New()

func random___byte(f *faker.Faker, limits ...string) []byte {
	if f == nil {
		f = &defaultFaker
	}

	return []byte(random_string(f, limits...))
}

func random_bool(f *faker.Faker, limits ...string) bool {
	if f == nil {
		f = &defaultFaker
	}

	return f.Bool()
}

func random_decimal_Decimal(f *faker.Faker, limits ...string) decimal.Decimal {
	if f == nil {
		f = &defaultFaker
	}

	var precision int64 = 7
	var scale int64 = 3

	if len(limits) > 0 {
		precision, _ = strconv.ParseInt(limits[0], 10, 32)
	}

	if len(limits) > 1 {
		scale, _ = strconv.ParseInt(limits[1], 10, 32)
	}

	baseVal := f.Float32(10, -1, 1)
	for baseVal == -1 || baseVal == 0 || baseVal == 1 {
		baseVal = f.Float32(10, -1, 1)
	}

	precisionDecimal, _ := decimal.NewFromInt(10).PowInt32(int32(precision))
	val := decimal.
		NewFromFloat32(baseVal).
		Mul(precisionDecimal).
		Shift(int32(-1 * scale)).
		RoundDown(int32(scale))

	return val
}

func random_enums_Hashtype(f *faker.Faker, limits ...string) enums.Hashtype {
	if f == nil {
		f = &defaultFaker
	}

	var e enums.Hashtype
	all := e.All()
	return all[f.IntBetween(0, len(all)-1)]
}

func random_float32(f *faker.Faker, limits ...string) float32 {
	if f == nil {
		f = &defaultFaker
	}

	var precision int64 = 5
	var scale int64 = 2

	if len(limits) > 0 {
		precision, _ = strconv.ParseInt(limits[0], 10, 32)
	}

	if len(limits) > 1 {
		scale, _ = strconv.ParseInt(limits[1], 10, 32)
	}

	baseVal := f.Float64(10, -1, 1)
	for baseVal == -1 || baseVal == 0 || baseVal == 1 {
		baseVal = f.Float64(10, -1, 1)
	}

	scaleFloat := math.Pow10(int(scale))

	val := baseVal * math.Pow10(int(precision))
	val = math.Trunc(val) / scaleFloat

	return float32(val)
}

func random_float64(f *faker.Faker, limits ...string) float64 {
	if f == nil {
		f = &defaultFaker
	}

	var precision int64 = 5
	var scale int64 = 2

	if len(limits) > 0 {
		precision, _ = strconv.ParseInt(limits[0], 10, 32)
	}

	if len(limits) > 1 {
		scale, _ = strconv.ParseInt(limits[1], 10, 32)
	}

	baseVal := f.Float64(10, -1, 1)
	for baseVal == -1 || baseVal == 0 || baseVal == 1 {
		baseVal = f.Float64(10, -1, 1)
	}

	scaleFloat := math.Pow10(int(scale))

	val := baseVal * math.Pow10(int(precision))
	val = math.Trunc(val) / scaleFloat

	return val
}

func random_int16(f *faker.Faker, limits ...string) int16 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int16()
}

func random_int32(f *faker.Faker, limits ...string) int32 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int32()
}

func random_int64(f *faker.Faker, limits ...string) int64 {
	if f == nil {
		f = &defaultFaker
	}

	return f.Int64()
}

func random_string(f *faker.Faker, limits ...string) string {
	if f == nil {
		f = &defaultFaker
	}

	val := strings.Join(f.Lorem().Words(f.IntBetween(1, 5)), " ")
	if len(limits) == 0 {
		return val
	}
	limitInt, _ := strconv.Atoi(limits[0])
	if limitInt > 0 && limitInt < len(val) {
		val = val[:limitInt]
	}
	return val
}

func random_time_Time(f *faker.Faker, limits ...string) time.Time {
	if f == nil {
		f = &defaultFaker
	}

	year := time.Hour * 24 * 365
	min := time.Now().Add(-year)
	max := time.Now().Add(year)
	return f.Time().TimeBetween(min, max)
}
