#!/usr/bin/env python3
import argparse
import logging
import pprint
import requests

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument("username")
	parser.add_argument("password")
	parser.add_argument("--url", default="http://[::1]:3000")
	args = parser.parse_args()

	logging.basicConfig(level=logging.DEBUG)

	session = requests.Session()
	login = args.url + "/login"
	logging.info("Logging in to %s", login)
	response = session.post(login, data={"password": args.password, "username": args.username})
	logging.info("Response: %s", response.status_code)
	if not response.ok:
		return

	client = args.url + "/api/client/ios"
	logging.info("GET %s", client)
	response = session.get(client)
	logging.info("Response: %s", response.status_code)
	if not response.ok:
		return

	logging.info("Writing response.json")
	with open("response.json", "w") as f:
		f.write(pprint.pformat(response.json()))
	logging.info("Done")

if __name__ == "__main__":
	main()
	
